aliyun:
  accessKey: $ALIYUN_ACCESSKEY
  accessKeySecret: $ALIYUN_ACCESSKEY_SECRET
  endpoint: ecs-cn-hangzhou.aliyuncs.com
  permissions:
    - name: trojan
      region: cn-hongkong
      securityGroupId: sg-j6c7mqm1h3u2w98f11i9
      portRange: 80/80
      comment: hz
    - name: trojan
      region: cn-hongkong
      securityGroupId: sg-j6c7mqm1h3u2w98f11i9
      portRange: 443/443
      comment: hz
    - name: n2n
      region: cn-hangzhou
      securityGroupId: sg-bp1gi2ckefjvdax5kot5
      portRange: 7777/7777
      comment: hz
